---
title: "Replication"
author: "Arnob Alam"
date: "December 19, 2016"
output:
  html_document: default
  pdf_document: default
  word_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
source("src/sem_macro_main.R")
```

```{r, results='asis'}

main_vars <- cbind(
  "FX Swap deviation" = 100 * (swap_implied_rates - usd_libor),
  "CDS (European)" = 100 * european_fin_cds,
  "CDS (US)" = 100 * na_ig_cdx,
  "Broad - OIS spread" = 100 * (eurodollar - usd_ois),
  "Libor - OIS spread" = 100 * (usd_libor - usd_ois))

reported_precrisis <-data.frame(
  mean = c(0.171, 0.703, 2.263, 0.806, 0.690),
  max = c(0.446, 1.610, 4.695, 1.201, 1.635),
  min = c(-0.272, 0.205, 0.846, 0.250, 0.243),
  stdev =c(0.115, 0.288, 0.784, 0.207, 0.142),
  row.names = c(
    "FX Swap Deviation", "CDS (European)", "CDS (US)", "Broad - OIS Spread","Libor - OIS Spread"))


reported_crisis <-data.frame(
  mean = c(0.831, 1.182, 5.079, 2.6796, 1.803),
  max = c(2.602, 1.560, 8.542, 4.826, 3.644),
  min = c(-0.093, 0.920, 3.571, 1.234, 0.893),
  stdev =c(0.511, 0.136, 1.064, 1.059, 0.738),
  row.names = c(
    "FX Swap Deviation", "CDS (European)", "CDS (US)", "Broad - OIS Spread","Libor - OIS Spread"))


precrisis_start <- "2007-08-09"
precrisis_end <- "2008-09-12"

crisis_start <- "2008-09-15"
crisis_end <- "2009-01-31"

summary(window(
  main_vars, 
  start = precrisis_start, 
  end = precrisis_end))
#print(precrisis)

# xtable(t(reported_precrisis), digits = 3)

summary(window(
  main_vars, 
  start = crisis_start, 
  end = crisis_end))

xtable(crisis, digits = 3)
xtable(reported_crisis, digits = 3)

```


```{r}
overnight_auction_dates <- as.POSIXct(c("2008-10-15", "2008-10-14", "2008-10-10", "2008-10-09",
                             "2008-10-07", "2008-10-06", "2008-10-03", "2008-10-02",
                             "2008-10-01", "2008-09-30", "2008-09-29", "2008-09-26",
                             "2008-09-25", "2008-09-24", "2008-09-23", "2008-09-22",
                             "2008-09-19", "2008-09-18"), tz="UTC")

one_month_auction_dates <- as.POSIXct(c("2007-12-17", "2008-01-14", "2008-03-25", "2008-04-22",
                                        "2008-05-06", "2008-05-20", "2008-06-03", "2008-06-17",
                                        "2007-08-01", "2008-07-15", "2008-07-29","2008-08-13", 
                                        "2008-08-26", "2008-09-10", "2008-09-23"), 
                                      tz="UTC") 

ecb1 <- zoo(0, time(main_vars))
indices <- which(index(ecb1) %in% overnight_auction_dates)
ecb1[indices] <- 1
main_vars <- cbind(main_vars, ecb1)

ecb3 <- zoo(0, time(main_vars))
indices2 <- which(index(ecb3) %in% one_month_auction_dates)
ecb3[indices2] <- 1
main_vars <- cbind(main_vars, ecb3)

commitment <- zoo(0, time(main_vars))
indices3 <- (index(main_vars) > as.POSIXct("2008-07-30", tz="UTC"))
commitment[indices3] <- 1
main_vars <- cbind(main_vars, commitment)

```
```{r}
names(main_vars) <- c("fx_swap_deviation", "cds_european", "cds_us", "broad_ois", "libor_ois", "ecb1", "ecb3", "commitment")
precrisis_model <- lm(fx_swap_deviation ~ cds_european + cds_us + broad_ois + libor_ois + ecb3 + commitment, 
                     data = window(main_vars, 
                                   start = precrisis_start, 
                                   end = precrisis_end), na.action = na.omit)
```